version: '3'
services:
  app:
    build: .
    ports:
      #for spring boot instances.
      - "8080:8080"
      - "8081:8080"
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ardecorify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test123
    depends_on:
      #create database in the container below.
      - postgres

  postgres:
    container_name: ardecorify-db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: ardecorify