version: '3'
services:
  ardecorify:
    build:
      context: .
      dockerfile: Dockerfile
    image: ardecorify-v2:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ardecorify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test123
    depends_on:
      - postgres

  postgres:
    container_name: ardecorify-db
    image: postgres:16
    ports:
      - "${PGPORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: ardecorify
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: